name: Serveo Tunnel

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  serveo:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
    - name: Install SSH and start tunnel
      run: |
        sudo apt-get update
        sudo apt-get install -y openssh-client
        ssh -o StrictHostKeyChecking=no -R github-runner:22:localhost:22 serveo.net
