name: SSHX Tunnel
on: workflow_dispatch

jobs:
  sshx:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    
    steps:
    - name: Install SSHX
      run: |
        curl -sSf https://sshx.io/get | sh
        echo "$HOME/.sshx/bin" >> $GITHUB_PATH
    
    - name: Start SSHX in background
      run: |
        nohup sshx > sshx.log 2>&1 &
        echo $! > sshx.pid
        sleep 10
        cat sshx.log
    
    - name: Send Telegram
      run: |
        URL=$(grep -o 'https://[^ ]*' sshx.log | head -1)
        curl -s -X POST "https://api.telegram.org/bot8179030443:AAEL8dF4cxeAQ3bLbsb_CrAHI2nfcWK12XE/sendMessage" \
          -d chat_id="7309086003" \
          -d text="SSHX: $URL" || echo "Telegram failed"
    
    - name: Wait
      run: sleep 21600
