name: Serveo Tunnel

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  serveo:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
    - name: Install and setup SSH server
      run: |
        sudo apt-get update
        sudo apt-get install -y openssh-server openssh-client
        
        # Создаем пароль для пользователя runner (или используем существующий)
        echo "runner:password123" | sudo chpasswd
        
        # Разрешаем парольную аутентификацию
        sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
        sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
        
        # Запускаем SSH сервер
        sudo service ssh start
        sudo service ssh status

    - name: Start Serveo tunnel
      run: |
        ssh -o StrictHostKeyChecking=no -R github-runner:22:localhost:22 serveo.net
