name: VNC via Cloudflare Quick Tunnel

on: [workflow_dispatch]

jobs:
  vnc:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Install VNC
      run: |
        Invoke-WebRequest -Uri "https://www.tightvnc.com/download/2.8.81/tightvnc-2.8.81-gpl-setup-64bit.msi" -OutFile "tightvnc.msi"
        Start-Process msiexec -ArgumentList "/i tightvnc.msi /quiet /norestart" -Wait
        Start-Sleep -Seconds 10
        $vncPath = "C:\Program Files\TightVNC\tvnserver.exe"
        & "$vncPath" -service -start
        Start-Sleep -Seconds 5
        & "$vncPath" -controlservice -password Pass123!

    - name: Start Quick Tunnel
      run: |
        Invoke-WebRequest -Uri "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe" -OutFile "cloudflared.exe"
        
        # Запускаем quick tunnel (не требует аутентификации)
        $tunnelJob = Start-Job -ScriptBlock {
            $process = Start-Process -FilePath ".\cloudflared.exe" -ArgumentList "tunnel --url tcp://localhost:5900" -PassThru -NoNewWindow
            return $process.Id
        }
        
        # Ждем и получаем URL
        Start-Sleep -Seconds 10
        
        # Cloudflared сам покажет URL в консоли
        Write-Host "================================================"
        Write-Host "🚀 QUICK TUNNEL STARTED"
        Write-Host "Check logs above for connection URL"
        Write-Host "Format: random-string.try.cloudflare.com"
        Write-Host "VNC Password: Pass123!"
        Write-Host "================================================"
        
        # Ждем 6 часов
        Start-Sleep -Seconds 21600
