name: Browser VNC

on: [workflow_dispatch]

jobs:
  novnc:
    runs-on: windows-latest
    
    steps:
    - name: Setup noVNC environment
      run: |
        # Установка VNC и noVNC
        choco install tightvnc -y
        # Запуск VNC сервера
        "C:\Program Files\TightVNC\tvnserver.exe" -register
        "C:\Program Files\TightVNC\tvnserver.exe" -start
        
    - name: Expose VNC via Tunnel
      run: |
        $subdomain = "novnc-${{ github.run_id }}"
        npx localtunnel --port 5900 --subdomain $subdomain &
        Write-Host "Connect via VNC client to: $subdomain.loca.lt:5900"
        Start-Sleep 21600
