name: VNC via Serveo

on: [workflow_dispatch]

jobs:
  vnc:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Install OpenSSH Client
      run: |
        # Устанавливаем SSH клиент в Windows
        Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0

    - name: Install TightVNC
      run: |
        Invoke-WebRequest -Uri "https://www.tightvnc.com/download/2.8.81/tightvnc-2.8.81-gpl-setup-64bit.msi" -OutFile "tightvnc.msi"
        Start-Process msiexec -ArgumentList "/i tightvnc.msi /quiet /norestart" -Wait

    - name: Configure VNC
      run: |
        Start-Sleep -Seconds 5
        $vncPath = "C:\Program Files\TightVNC\tvnserver.exe"
        & "$vncPath" -service -start
        Start-Sleep -Seconds 3
        & "$vncPath" -controlservice -password Pass123!

    - name: Start Serveo Tunnel
      run: |
        $subdomain = "vnc-${{ github.run_id }}-${{ github.run_attempt }}"
        Write-Host "Starting Serveo tunnel..."
        
        # Запускаем SSH туннель через Serveo
        $tunnelJob = Start-Job -ScriptBlock {
            ssh -o StrictHostKeyChecking=no -R ${using:subdomain}:80:localhost:5900 serveo.net
        }
        
        Write-Host "================================================"
        Write-Host "VNC Connection Info:"
        Write-Host "Address: ${subdomain}.serveo.net"
        Write-Host "Port: 5900" 
        Write-Host "Password: Pass123!"
        Write-Host "================================================"
        
        # Ждем 6 часов
        Start-Sleep -Seconds 21600
