name: VNC via Cloudflare TCP Tunnel

on: [workflow_dispatch]

env:
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

jobs:
  vnc:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Install VNC
      run: |
        Invoke-WebRequest -Uri "https://www.tightvnc.com/download/2.8.81/tightvnc-2.8.81-gpl-setup-64bit.msi" -OutFile "tightvnc.msi"
        Start-Process msiexec -ArgumentList "/i tightvnc.msi /quiet /norestart" -Wait
        Start-Sleep -Seconds 10
        $vncPath = "C:\Program Files\TightVNC\tvnserver.exe"
        & "$vncPath" -service -start
        Start-Sleep -Seconds 5
        & "$vncPath" -controlservice -password Pass123!

    - name: Install Cloudflared
      run: |
        Invoke-WebRequest -Uri "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe" -OutFile "cloudflared.exe"

    - name: Create TCP Tunnel
      run: |
        # Устанавливаем API токен как переменную окружения (уже сделано через env)
        # Создаем туннель с уникальным именем
        $tunnelName = "vnc-${{ github.run_id }}-${{ github.run_attempt }}"
        Write-Host "Creating tunnel: $tunnelName"

        # Создаем туннель и получаем его ID
        .\cloudflared.exe tunnel create $tunnelName
        # Настраиваем туннель на перенаправление TCP трафика
        # Создаем конфиг файл для туннеля
        $tunnelConfig = @"
tunnel: $tunnelName
credentials-file: .cloudflared/$tunnelName.json
ingress:
  - hostname: $tunnelName.try.cloudflare.com
    service: tcp://localhost:5900
  - service: http_status:404
"@
        $tunnelConfig | Out-File -FilePath "config.yml" -Encoding ASCII

        # Назначаем DNS запись для туннеля
        .\cloudflared.exe tunnel route dns $tunnelName $tunnelName

        Write-Host "Tunnel created and DNS configured"

    - name: Run Tunnel
      run: |
        $tunnelName = "vnc-${{ github.run_id }}-${{ github.run_attempt }}"
        Write-Host "================================================"
        Write-Host "🚀 VNC TUNNEL STARTED"
        Write-Host "VNC Address: $tunnelName.try.cloudflare.com:5900"
        Write-Host "VNC Password: Pass123!"
        Write-Host "================================================"

        # Запускаем туннель
        .\cloudflared.exe tunnel run $tunnelName
